// home page
export * from './Frame/frame'
export * from './CustomCursor/cursor'
export * from './Header/header'
export * from './Pagination/pagination'
export * from './AnimeTrigger/animeTrigger'
export * from './Button/button'
export * from './Lock/lock'
export * from './SVGLetters/mail'
export * from './WaveLetters/waveLetters'
export * from './Canvas/canvas'
export * from './Loader/loader'
export * from './SplitLetters/splitLetter'
export * from './Display/display'
export * from './Sliders/Portable/framerSlider'
export * from './Sliders/Mobile/slickSlider'